### ISSUE TITLE
[Fedora34 - Gnome 40] v11 works, v12 doesn't

### ISSUE THREAD

**Issue by Ramalama2** [daitj/gnome-display-brightness-ddcutil#20]
Hi, gnome crashes with v12.
While v11 works perfectly.

`Mai 05 13:00:36 fedora gnome-shell[46539]: JS ERROR: ReferenceError: Gtk is not defined
                                           addSettingsItem@/home/rama/.local/share/gnome-shell/extensions/display-brightness-ddcutil@themightydeity.github.com/extension.js:138:35
                                           reloadMenuWidgets@/home/rama/.local/share/gnome-shell/extensions/display-brightness-ddcutil@themightydeity.github.com/extension.js:174:5
                                           parseDisplaysInfoAndAddToPanel/</</<@/home/rama/.local/share/gnome-shell/extensions/display-brightness-ddcutil@themightydeity.github.com/extension.js:229:50
                                           spawnWithCallback/<@/home/rama/.local/share/gnome-shell/extensions/display-brightness-ddcutil@themightydeity.github.com/convenience.js:141:19`

**Comment by daitj** [comment]
@Ramalama2 

Gtk is imported in extension.js in line 21, I actually added it in version 12. It is weird that it shows an error like that. 

Could you edit line 139 of `home/rama/.local/share/gnome-shell/extensions/display-brightness-ddcutil@themightydeity.github.com/extension.js`

and replace `new Gtk.Button` with `new imports.gi.Gtk.Button`

Then restart your gnome shell, let me know what happens?

**Comment by Ramalama2** [comment]
[shell-log.txt](https://github.com/daitj/gnome-display-brightness-ddcutil/files/6427207/shell-log.txt)

It loooks way more complicated.
libgtk is crashing, probably it isn't even anything in your code, i try it now on x11 instead of wayland xD

**Comment by Ramalama2** [comment]
Yes, on Xorg it's working perfectly.
Both versions works und Xorg :-(
new Gtk.Button / new imports.gi.Gtk.Button

On wayland it crashes xD

**Comment by daitj** [comment]
So old version works fine under wayland right?

May be you could revert the changes I did in line 21 in extension.js

`const {GLib, Gio, St, Gtk} = imports.gi;` to `const {GLib, Gio, St} = imports.gi;`

Basically removing the import of Gtk.

**Comment by Ramalama2** [comment]
Line 21: const {GLib, Gio, St} = imports.gi;
Line 139: new imports.gi.Gtk.Button
= Crash

Line 21: const {GLib, Gio, St} = imports.gi;
Line 139: new Gtk.Button
= Works, reload button is there, gnome doesnt crash.
But the extension is in the "initializing" mode forever and i don't get the Brightness slider of the display.
Like the menu and everything is here, just it doesn't recognize the display.

https://extensions.gnome.org/extension/2645/brightness-control-using-ddcutil/
Shell v40 + Extension v11
Works perfectly.

I compared with diff both versions, there are more changes between them like:
function onPanelChange
function connectPanelSignals
function disconnectPanelSignals
Those 3 functions doesn't exist in the new v12/git.

Cheers

**Comment by daitj** [comment]
You said that this works right?
```
Line 21: const {GLib, Gio, St} = imports.gi;
Line 139: new Gtk.Button
```
but gets stuck in "Initializing", can you check the logs. I would like to see if extension is throwing any error.
Also, can you press the reload button during that phase ?

The other three functions that were removed were there to repopulate the displays in the menu when gnome's panel  position changes happen, which didn't seem to be necessary.

**Comment by saknl** [comment]
I have the same issue on Fedora 34 too. When booting with the extension enabled, the gnome session crashes immediately after login and Gnome disables all extensions. Booting with the extension disabled and enable it after login does work.

**Comment by daitj** [comment]
@saknl  are you also using Wayland and could you post shell log?

I will try to check this later today, I need to figure this out if it is some upstream bug or some problem in my extension. 
I need to figure out why Gtk is not defined in wayland during first initialize of extension. 

Could you both @saknl  and @Ramalama2 send me the full version of gnome-shell you are using?

**Comment by saknl** [comment]
@daitj Yes I'm using Wayland. I'm not sure how to get my gnome-shell log. I did this one using `journalctl -b`.
[log.txt](https://github.com/daitj/gnome-display-brightness-ddcutil/files/6434931/log.txt)
I'm using gnome-shell 40.0.0

**Comment by daitj** [comment]
@saknl  I think this should work `journalctl -b /usr/bin/gnome-shell`

**Comment by saknl** [comment]
@daitj Thank you. There you go: 
[log.txt](https://github.com/daitj/gnome-display-brightness-ddcutil/files/6437531/log.txt)

**Comment by daitj** [comment]
@saknl I cannot see any useful error on that log.

@saknl  and @Ramalama2  I could reproduce the error in a virtual Fedora but I have no clue if this is Fedora issue or GNOME issue. I have a feeling that Gtk is not initialize in time for some reason, which is causing the problem. This also explains why you can enable the extension after logging in and it works. But anyway I will try to find right place to report it. In the mean time, if you both of you edit line number 96 in `extension.js`
change 
```JS
        }, 1);
```
to
```JS
        }, 1000);

```
This will add delay for populating settings and reload button in the menu by 1000 milis, which solved the issue for me, extension worked without crash. You can increase that also if it doesn't work in your system.

@saknl You can find the `extension.js` here /home/lukas/.local/share/gnome-shell/extensions/display-brightness-ddcutil@themightydeity.github.com/extension.js

**Comment by saknl** [comment]
Thank you a lot! Editing extension.js didn't work, but with the new commit you just did everything works as expected.

**Comment by Ramalama2** [comment]
Thanks @daitj 
v13 works perfectly.

Sorry i wasn online yesterday, real life :-(

Can we consider this fixed now or does someone still wants to test something?

**Comment by daitj** [comment]
I was my bad, there was some remnant code when I copied some components from settings. 

That Gtk button was never populated, so I still do not know why in wayland it was crashing. But anyway removing it fixed the issue. 
I will follow up with the gnome-shell-extension project peeps, to understand more. This can be closed.
